version = "3.7.14"
runner.dialect = scala213
rewrite.rules = [Imports, SortModifiers]
rewrite.imports.sort = original
maxColumn = 100
docstrings.style = SpaceAsterisk
docstrings.blankFirstLine = yes
align.preset = none
newlines.avoidForSimpleOverflow = [slc]
includeNoParensInSelectChains = true